# safelist
branches:
  only:
  - master
  - v0.99a
  - v0.99b
  - v0.99c
  - v0.99d
  - v0.99e
  
before_install:
- sudo apt-get update -qq

language: C
compiler: gcc

install: make
script: make test


